- IMS.Application/Features/Products/Commands/AddEditProductCommandHandler.cs
- IMS.Application/Features/Products/Queries/GetAllProductsQuery.cs
- IMS.Infrastructure/Interface/Products/IProductRepository.cs
- IMS.Infrastructure/Services/Products/ProductRepository.cs
- IMS.Shared/Constants/ApiEndpoints.cs
- IMS.Shared/Interface/Product/IProductService.cs
- IMS.Shared/RequestDto/ProductDTOs/AddProductDto.cs
- IMS.Shared/RequestDto/ProductDTOs/ProductFilterDto.cs
- IMS.Shared/Services/Product/ProductService.cs
- IMS.WebAPI/Controllers/ProductsController.cs
- IMS.WebApp/IMS.WebApp.Client/Pages/Products/ProductForm.razor
- IMS.WebApp/IMS.WebApp.Client/Pages/Products/ProductFormDialog.razor
- IMS.WebApp/IMS.WebApp.Client/Pages/Products/ProductList.razor
Add Edit Product Details, Product List Filtering, sorting and searching
> Add Edit Product Details, Product List Filtering, sorting and searching

- IMS.Shared/Constants/ApiEndpoints.cs
- IMS.Shared/Interface/Auth/IAuthService.cs
- IMS.Shared/Services/Auth/AuthService.cs
- IMS.WebApp/IMS.WebApp.Client/Authentication/AuthStateService.cs
- IMS.WebApp/IMS.WebApp.Client/Authentication/ITokenService.cs
- IMS.WebApp/IMS.WebApp.Client/Authentication/TokenService.cs
- IMS.WebApp/IMS.WebApp.Client/IMS.WebApp.Client.csproj
- IMS.WebApp/IMS.WebApp/Components/App.razor
- IMS.WebApp/IMS.WebApp/Components/Layout/MainLayout.razor
- IMS.WebApp/IMS.WebApp/Components/Layout/NavMenu.razor
- IMS.WebApp/IMS.WebApp/Components/Pages/Login.razor
- IMS.WebApp/IMS.WebApp/Components/Pages/Signup.razor
- IMS.WebApp/IMS.WebApp/Components/Routes.razor
- IMS.WebApp/IMS.WebApp/Program.cs
> Added the login singup page.

- IMS.WebApp/IMS.WebApp.Client/Pages/Products/ProductDetail.razor
- IMS.WebApp/IMS.WebApp.Client/Pages/Products/ProductList.razor
- IMS.WebApp/IMS.WebApp/Components/Layout/NavMenu.razor
- IMS.WebApp/IMS.WebApp/Components/Layout/Public/PublicLayout.razor
- IMS.WebApp/IMS.WebApp/Components/Layout/Shared/Footer.razor
- IMS.WebApp/IMS.WebApp/Components/Layout/Shared/Header.razor
- IMS.WebApp/IMS.WebApp/Components/Pages/Login.razor
- IMS.WebApp/IMS.WebApp/Components/Pages/Public/Home.razor
Footer design Fixed, Public Layout Design
> Footer design Fixed, Public Layout Design

- IMS.Application/Features/Cart/Command/AddToCartCommand.cs
- IMS.Application/Features/Cart/Command/EditCartCommand.cs
- IMS.Application/Features/Cart/Handlers/AddToCartCommandHandler.cs
- IMS.Application/Features/Cart/Handlers/EditCartCommandHandler.cs
- IMS.Application/Features/Cart/Handlers/GetCartItemsQueryHandler.cs
- IMS.Application/Features/Cart/Queries/GetCartItemsQuery.cs
- IMS.Core/Entities/Cart.cs
- IMS.Core/Entities/Category.cs
- IMS.Core/RequestDto/AddCartItemDto.cs
- IMS.Core/RequestDto/CartDto.cs
- IMS.Infrastructure/Interface/Cart/ICartRepository.cs
- IMS.Infrastructure/Interface/Category/ICategoryRepository.cs
- IMS.Infrastructure/Migrations/20241213072226_cart.Designer.cs
- IMS.Infrastructure/Migrations/20241213072226_cart.cs
- IMS.Infrastructure/Persistence/ApplicationDbContext.cs
- IMS.Infrastructure/Services/Cart/CartRepository.cs
- IMS.WebAPI/Controllers/CartController.cs
- IMS.WebAPI/Program.cs
Feature/a implement endpoints for cart
> Added the endpoint for the cart

- IMS.Shared/Constants/ApiEndpoints.cs
- IMS.Shared/Interface/Cart/ICartService.cs
- IMS.Shared/RequestDto/CartDTOs/AddCartItemDto.cs
- IMS.Shared/RequestDto/CartDTOs/CartDto.cs
- IMS.Shared/Services/Cart/CartService.cs
- IMS.WebAPI/Controllers/CartController.cs
- IMS.WebApp/IMS.WebApp.Client/Pages/Cart/ViewCart.razor
- IMS.WebApp/IMS.WebApp.Client/Pages/Products/ProductDetail.razor
- IMS.WebApp/IMS.WebApp/Program.cs
> ViewCartDetails

- IMS.Shared/Constants/ApiEndpoints.cs
- IMS.Shared/Interface/Cart/ICartService.cs
- IMS.Shared/RequestDto/CartDTOs/AddCartItemDto.cs
- IMS.Shared/RequestDto/CartDTOs/CartDto.cs
- IMS.Shared/Services/Cart/CartService.cs
- IMS.WebAPI/Controllers/CartController.cs
- IMS.WebApp/IMS.WebApp.Client/Pages/Cart/ViewCart.razor
- IMS.WebApp/IMS.WebApp.Client/Pages/Products/ProductDetail.razor
- IMS.WebApp/IMS.WebApp/Components/Layout/Shared/Header.razor
- IMS.WebApp/IMS.WebApp/Program.cs
> Dev to Main

- IMS.Shared/Constants/ApiEndpoints.cs
- IMS.Shared/Interface/Cart/ICartService.cs
- IMS.Shared/Services/Cart/CartService.cs
- IMS.WebAPI/Controllers/CartController.cs
- IMS.WebApp/IMS.WebApp.Client/Pages/Cart/ViewCart.razor
- IMS.WebApp/IMS.WebApp.Client/Pages/Products/ProductDetail.razor
- IMS.WebApp/IMS.WebApp/Components/Layout/Shared/Footer.razor
Cart Details - Add, Edit, Listing
> Cart Details - Add, Edit, Listing

- IMS.WebApp/IMS.WebApp.Client/Authentication/AuthStateService.cs
- IMS.WebApp/IMS.WebApp.Client/IMS.WebApp.Client.csproj
- IMS.WebApp/IMS.WebApp.Client/Pages/Cart/ViewCart.razor
- IMS.WebApp/IMS.WebApp.Client/Pages/Products/ProductDetail.razor
- IMS.WebApp/IMS.WebApp/Components/Layout/MainLayout.razor
- IMS.WebApp/IMS.WebApp/Components/Layout/NavMenu.razor
- IMS.WebApp/IMS.WebApp/Components/Layout/Public/LoginLayout.razor
- IMS.WebApp/IMS.WebApp/Components/Layout/Shared/Header.razor
- IMS.WebApp/IMS.WebApp/Components/Pages/Login.razor
- IMS.WebApp/IMS.WebApp/Components/Routes.razor
- IMS.WebApp/IMS.WebApp/Program.cs
> Fix state management issue.

- IMS.WebApp/IMS.WebApp.Client/Authentication/AuthStateService.cs
- IMS.WebApp/IMS.WebApp/Components/Layout/NavMenu.razor
- IMS.WebApp/IMS.WebApp/Components/Pages/Login.razor
- IMS.WebApp/IMS.WebApp/Components/Routes.razor
> Fix the role route

- IMS.Application/Features/Auth/Queries/GetAllUserCommand.cs
- IMS.Application/Features/Auth/Queries/GetAllUserCommandHandler.cs
- IMS.WebAPI/Controllers/AuthController.cs
Added a new endpoint to get all the user.
> Added a new endpoint to get all the user.

- IMS.WebApp/IMS.WebApp.Client/Pages/Admin/AdminDashboard.razor
- IMS.WebApp/IMS.WebApp.Client/Pages/Customer/CustomerList.razor
Dashboard changes- Dashboard Page
> Dashboard changes- Dashboard Page

- IMS.Shared/Services/Shared/CartStateService.cs
- IMS.WebApp/IMS.WebApp.Client/Pages/Cart/ViewCart.razor
- IMS.WebApp/IMS.WebApp.Client/Pages/Payment/OrderSummary.razor
- IMS.WebApp/IMS.WebApp/Program.cs
Implemented Order summary for Cart Items
> Implemented Order summary for Cart Items

- IMS.Infrastructure/Services/Products/ProductRepository.cs
- IMS.Shared/Constants/ApiEndpoints.cs
- IMS.Shared/Interface/Auth/IAuthService.cs
- IMS.Shared/RequestDto/UserDTOs/ApplicationUserDto.cs
- IMS.Shared/Services/Auth/AuthService.cs
- IMS.WebApp/IMS.WebApp.Client/Pages/Customer/CustomerList.razor
- IMS.WebApp/IMS.WebApp.Client/Pages/Products/ProductFormDialog.razor
Customer List Implementation-Edit Product Details Size
> Customer List Implementation-Edit Product Details Size

- IMS.Infrastructure/Services/Products/ProductRepository.cs
- IMS.Shared/RequestDto/ProductDTOs/AddProductDto.cs
- IMS.WebApp/IMS.WebApp.Client/Pages/Products/ProductFormDialog.razor
- IMS.WebApp/IMS.WebApp/Components/Layout/NavMenu.razor
Validation Product Add/Edit Form
> Validation Product Add/Edit Form

- IMS.WebApp/IMS.WebApp.Client/Pages/Products/ProductList.razor
> Fixes for Error

- IMS.Application/Features/Order/Command/AddOrderCommand.cs
- IMS.Application/Features/Order/Command/AddOrderCommandHandler.cs
- IMS.Application/Features/Order/Queries/GetAllOrdersQuery.cs
- IMS.Application/Features/Order/Queries/GetAllOrdersQueryHandler.cs
- IMS.Core/Common/Entities/OrderProductDetails.cs
- IMS.Core/Entities/Orders.cs
- IMS.Core/RequestDto/OrderDto.cs
- IMS.Infrastructure/Interface/Order/IOrderRopository.cs
- IMS.Infrastructure/Migrations/20241218122211_ordermodify.Designer.cs
- IMS.Infrastructure/Migrations/20241218122211_ordermodify.cs
- IMS.Infrastructure/Persistence/ApplicationDbContext.cs
- IMS.Infrastructure/Services/OrdersRepository.cs
- IMS.WebAPI/Controllers/OrdersController.cs
- IMS.WebAPI/Program.cs
> added code for orders .

- IMS.WebAPI/Controllers/TwoFactorAuthController.cs
> Bug fix for Two Factor Auth

- IMS.WebApp/IMS.WebApp.Client/Pages/Products/ProductDetail.razor
- IMS.WebApp/IMS.WebApp.Client/Pages/Products/ProductList.razor
Code committed for thumbnail chagnes
> Code committed for thumbnail chagnes

- IMS.WebApp/IMS.WebApp.Client/Pages/Products/ProductList.razor
- IMS.WebApp/IMS.WebApp/Components/Pages/TwoFactorAuth.razor
Issue fix for Two Factor Auth , Product List
> Issue fix for Two Factor Auth , Product List

- IMS.WebApp/IMS.WebApp.Client/Pages/Products/ProductDetail.razor
- IMS.WebApp/IMS.WebApp.Client/Pages/Products/ProductList.razor
Price Fixes for ProductDetail and ProductList
> Price Fixes for ProductDetail and ProductList

- IMS.WebAPI/appsettings.json
> remove send grid key

- IMS.WebApp/IMS.WebApp/Components/Routes.razor
> Bug fix Routes

- IMS.Application/Features/Order/Queries/GetAllUserOrdersQuery.cs
- IMS.Application/Features/Order/Queries/GetAllUserOrdersQueryHandler.cs
- IMS.Application/Features/Order/Queries/GetOrderByIdQuery.cs
- IMS.Application/Features/Order/Queries/GetOrderByIdQueryHandler.cs
- IMS.Core/Common/Entities/OrderProductDetails.cs
- IMS.Infrastructure/Interface/Order/IOrderRopository.cs
- IMS.Infrastructure/Services/Order/OrdersRepository.cs
- IMS.Shared/Constants/ApiEndpoints.cs
- IMS.Shared/Interface/Order/IOrderService.cs
- IMS.Shared/RequestDto/orderDTOs/AddOrderDto.cs
- IMS.Shared/RequestDto/orderDTOs/GetOrderDto.cs
- IMS.Shared/Services/Order/OrderService.cs
- IMS.WebAPI/Controllers/OrdersController.cs
- IMS.WebApp/IMS.WebApp.Client/Pages/Order/MyOrder.razor
- IMS.WebApp/IMS.WebApp.Client/Pages/Payment/OrderSummary.razor
- IMS.WebApp/IMS.WebApp.Client/Pages/Products/OrderDetails.razor
- IMS.WebApp/IMS.WebApp.Client/Pages/Profile/UserProfile.razor
- IMS.WebApp/IMS.WebApp/Components/Layout/Shared/Header.razor
- IMS.WebApp/IMS.WebApp/Components/Pages/Login.razor
- IMS.WebApp/IMS.WebApp/Components/Routes.razor
- IMS.WebApp/IMS.WebApp/Program.cs
- IMS.WebApp/IMS.WebApp/appsettings.json
> my orders page implemented

- IMS.Shared/Constants/ApiEndpoints.cs
- IMS.WebApp/IMS.WebApp.Client/Pages/Checkout/OrderSummary.razor
Bug Fixed End points, Order Summary
> Bug Fixed End points, Order Summary

- IMS.Application/Features/Order/Command/CreateStripeCheckoutSessionCommandHandler.cs
- IMS.Core/Common/Entities/OrderProductDetails.cs
- IMS.Shared/RequestDto/orderDTOs/AddOrderDto.cs
- IMS.WebAPI/appsettings.json
- IMS.WebApp/IMS.WebApp.Client/Pages/Checkout/OrderSummary.razor
- IMS.WebApp/IMS.WebApp.Client/Pages/Payment/FailedPage.razor
- IMS.WebApp/IMS.WebApp.Client/Pages/Products/ProductDetail.razor
- IMS.WebApp/IMS.WebApp.Client/Pages/Products/ShareProduct.razor
- IMS.WebApp/IMS.WebApp/Components/Layout/Shared/Header.razor
- IMS.WebApp/IMS.WebApp/Components/Pages/Signup.razor
- IMS.WebApp/IMS.WebApp/appsettings.json
Product detail Changes, worked on changes for header,signup, order summary, shareProduct- dynamic urls
> Product detail Changes, worked on changes for header,signup, order summary, shareProduct- dynamic urls

- IMS.Shared/Common/GeolocationPosition.cs
- IMS.WebApp/IMS.WebApp.Client/Pages/Products/OrderDetails.razor
- IMS.WebApp/IMS.WebApp/Components/App.razor
- IMS.WebApp/IMS.WebApp/Components/Layout/Shared/Header.razor
- IMS.WebApp/IMS.WebApp/Components/Pages/Login.razor
- IMS.WebApp/IMS.WebApp/Components/Pages/Signup.razor
Worked on  headerSection-UserLocation
> Worked on  headerSection-UserLocation

- IMS.WebApp/IMS.WebApp/Components/Layout/Shared/Header.razor
> HeaderBug Fix

- IMS.Mobile/App.xaml.cs
- IMS.Mobile/MainPage.xaml.cs
- IMS.Mobile/MauiProgram.cs
- IMS.Mobile/Service/ProductService.cs
- IMS.WebAPI/Program.cs
- IMS.WebApp/IMS.WebApp.Client/Program.cs
- IMS.WebApp/IMS.WebApp/Program.cs
> Bug fix http client

- IMS.Application/Features/Products/Queries/GetAllProductsQuery.cs
- IMS.Core/Common/Helper/GenericBaseResult.cs
- IMS.Infrastructure/Interface/Products/IProductRepository.cs
- IMS.Infrastructure/Services/Products/ProductRepository.cs
- IMS.Shared/Interface/Product/IProductService.cs
- IMS.Shared/Services/Product/ProductService.cs
- IMS.WebAPI/Controllers/ProductsController.cs
- IMS.WebApp/IMS.WebApp.Client/Pages/Admin/AdminDashboard.razor
- IMS.WebApp/IMS.WebApp.Client/Pages/Products/ProductFormDialog.razor
- IMS.WebApp/IMS.WebApp.Client/Pages/Products/ProductList.razor
- IMS.WebApp/IMS.WebApp/Components/App.razor
InfiniteScroll Product List implementation
> InfiniteScroll Product List implementation

- IMS.Application/Features/Order/Queries/GetAllOrdersQueryHandler.cs
- IMS.Core/Common/Entities/OrderProductDetails.cs
- IMS.WebAPI/Controllers/OrdersController.cs
- IMS.WebApp/IMS.WebApp.Client/Pages/Checkout/OrderSummary.razor
- IMS.WebApp/IMS.WebApp.Client/Pages/Order/OrderList.razor
Improvement Changes to OrderSummary Pages
> Improvement Changes

- IMS.WebApp/IMS.WebApp.Client/Pages/Checkout/OrderSummary.razor
Order Summary Bug fix- Address
> Order Summary Bug fix- Address

- IMS.WebApp/IMS.WebApp.Client/Pages/Address/MyAddress.razor
- IMS.WebApp/IMS.WebApp.Client/Pages/Cart/ViewCart.razor
- IMS.WebApp/IMS.WebApp.Client/Pages/Profile/UserProfile.razor
> design changes

- IMS.WebApp/IMS.WebApp.Client/Pages/Checkout/OrderSummary.razor
- IMS.WebApp/IMS.WebApp.Client/Pages/Products/ProductList.razor
- IMS.WebApp/IMS.WebApp/Components/Layout/Public/PublicLayout.razor
code committed for the design changes.
> code committed for the design changes.

- IMS.Shared/Services/Cart/CartService.cs
- IMS.WebAPI/Controllers/CartController.cs
- IMS.WebApp/IMS.WebApp.Client/Pages/Cart/ViewCart.razor
> Bug-Fixes-Application-Testing

- IMS.WebApp/IMS.WebApp.Client/Pages/Products/ProductList.razor
- IMS.WebApp/IMS.WebApp/Components/Layout/Shared/Footer.razor
- IMS.WebApp/IMS.WebApp/Components/Layout/Shared/Header.razor
- IMS.WebApp/IMS.WebApp/Components/Pages/Signup.razor
> responsive-changes

- IMS.WebApp/IMS.WebApp.Client/Pages/Products/ProductDetail.razor
- IMS.WebApp/IMS.WebApp/Components/Layout/Public/PublicLayout.razor
breadcrumb fix, product detail fix
> breadcrumb fix, product detail fix

- IMS.Infrastructure/Services/Products/ProductRepository.cs
- IMS.WebApp/IMS.WebApp.Client/Pages/Products/ProductList.razor
Product List fix Filter and description
> Product List fix

- IMS.WebApp/IMS.WebApp.Client/Pages/Products/ProductList.razor
> removed scrollbar

- IMS.WebApp/IMS.WebApp.Client/Pages/Products/ProductList.razor
> Home Page Banner

- IMS.Shared/Services/Shared/CartStateService.cs
- IMS.WebApp/IMS.WebApp.Client/Pages/Cart/ViewCart.razor
- IMS.WebApp/IMS.WebApp/Components/Layout/Shared/Header.razor
Implemented user cart item count on header page
> Implemented user cart item count on header page
